spring:
  application:
    name: route-management
  datasource:
    url: jdbc:postgresql://localhost:5432/routemanagement
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  servlet:
    context-path: /route-management

route:
  max-transportations: 3
  max-flights: 1
  max-before-flight-transfers: 1
  max-after-flight-transfers: 1